// Generated by GitHub Copilot
import { Navigate } from "react-router-dom";

type Props = {
  isAuthenticated: boolean;
  children: JSX.Element;
};

export function ProtectedRoute({ isAuthenticated, children }: Props): JSX.Element {
  if (!isAuthenticated) {
    return <Navigate to="/login" replace />;
  }
  return children;
}
