# Generated by GitHub Copilot
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.db.prediction import Prediction
from app.models.schemas.annotation import AnnotationOut, DoctorAnnotation

router = APIRouter()


@router.post("/predict/{prediction_id}/annotate", response_model=AnnotationOut)
async def annotate_prediction(
    prediction_id: str,
    payload: DoctorAnnotation,
    db: AsyncSession = Depends(get_db),
) -> AnnotationOut:
    """Attach physician annotation to prediction for clinical review trail."""

    result = await db.execute(select(Prediction).where(Prediction.id == prediction_id))
    prediction = result.scalar_one_or_none()
    if prediction is None:
        raise HTTPException(status_code=404, detail="Prediction not found")

    prediction.doctor_notes = payload.notes
    prediction.is_reviewed = True
    prediction.reviewed_at = datetime.now(timezone.utc)
    await db.commit()

    return AnnotationOut(
        prediction_id=prediction_id,
        notes=payload.notes,
        saved_at=datetime.now(timezone.utc),
    )
