# Generated by GitHub Copilot
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

from fastapi import APIRouter, Depends
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.db.prediction import Prediction
from app.services.ml.model_loader import ModelRegistry

router = APIRouter()


@router.get("/stats")
async def stats(db: AsyncSession = Depends(get_db)) -> dict[str, object]:
    """Return dashboard KPIs and model runtime status snapshot."""

    now = datetime.now(timezone.utc)
    week_ago = now - timedelta(days=7)
    day_start = datetime(now.year, now.month, now.day, tzinfo=timezone.utc)

    total_scans = int((await db.execute(select(func.count(Prediction.id)))).scalar_one() or 0)
    scans_this_week = int(
        (
            await db.execute(
                select(func.count(Prediction.id)).where(Prediction.created_at >= week_ago)
            )
        ).scalar_one()
        or 0
    )
    scans_today = int(
        (
            await db.execute(
                select(func.count(Prediction.id)).where(Prediction.created_at >= day_start)
            )
        ).scalar_one()
        or 0
    )
    average_confidence = float(
        (await db.execute(select(func.avg(Prediction.confidence)))).scalar_one() or 0.0
    )

    grade_counts = {str(i): 0 for i in range(5)}
    grade_rows = await db.execute(
        select(Prediction.dr_grade, func.count(Prediction.id)).group_by(Prediction.dr_grade)
    )
    for grade, count in grade_rows.all():
        grade_counts[str(int(grade))] = int(count)

    avg_inference_ms = int(
        (await db.execute(select(func.avg(Prediction.inference_ms)))).scalar_one() or 0
    )
    registry = ModelRegistry.get_instance()

    # Read model accuracy from training history
    history_path = Path("ml_models/training_history.json")
    model_accuracy = 0.0
    model_auc = 0.0
    if history_path.exists():
        try:
            history = json.loads(history_path.read_text(encoding="utf-8"))
            model_accuracy = history.get("test_accuracy", 0.0)
            model_auc = history.get("test_auc", 0.0)
        except Exception:
            pass

    return {
        "total_scans": total_scans,
        "scans_this_week": scans_this_week,
        "scans_today": scans_today,
        "average_confidence": average_confidence,
        "model_accuracy": model_accuracy,
        "model_auc": model_auc,
        "grade_distribution": grade_counts,
        "model_status": {
            "tier2_loaded": True,
            "tier1_loaded": True,
            "gpu_available": registry.gpu_available,
            "avg_inference_ms": avg_inference_ms,
        },
    }


@router.get("/recent-scans")
async def recent_scans(db: AsyncSession = Depends(get_db)) -> list[dict[str, object]]:
    """Return recent scan rows for dashboard table rendering."""

    rows = await db.execute(
        select(Prediction).order_by(Prediction.created_at.desc()).limit(10)
    )
    return [
        {
            "prediction_id": str(row.id),
            "patient_id": str(row.patient_id) if row.patient_id else None,
            "grade": row.dr_grade,
            "confidence": row.confidence,
            "model": row.model_used,
            "time": row.created_at.isoformat() if row.created_at else None,
        }
        for row in rows.scalars().all()
    ]


@router.get("/grade-distribution")
async def grade_distribution(db: AsyncSession = Depends(get_db)) -> dict[str, int]:
    """Return aggregate count by DR grade for charting endpoints."""

    counts = {str(i): 0 for i in range(5)}
    rows = await db.execute(
        select(Prediction.dr_grade, func.count(Prediction.id)).group_by(Prediction.dr_grade)
    )
    for grade, count in rows.all():
        counts[str(int(grade))] = int(count)
    return counts
