# Generated by GitHub Copilot
from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
async def health() -> dict[str, str]:
    """Liveness probe endpoint for process-level health checks."""

    return {"status": "ok"}


@router.get("/ready")
async def ready() -> dict[str, str]:
    """Readiness probe endpoint for dependency-aware startup checks."""

    return {"status": "ready"}
