# Generated by GitHub Copilot
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.db.prediction import Prediction
from app.models.schemas.patient import PatientCreate, PatientOut, PatientUpdate
from app.services.patient_service import PatientService

router = APIRouter()
service = PatientService()


@router.get("", response_model=list[PatientOut])
async def list_patients(db: AsyncSession = Depends(get_db)) -> list[PatientOut]:
    """List all patients for clinic workflow and search interfaces."""

    return [PatientOut.model_validate(p) for p in await service.list_patients(db)]


@router.post("", response_model=PatientOut)
async def create_patient(payload: PatientCreate, db: AsyncSession = Depends(get_db)) -> PatientOut:
    """Create a patient profile used for longitudinal diabetic eye care."""

    patient = await service.create_patient(db, payload)
    return PatientOut.model_validate(patient)


@router.put("/{patient_id}", response_model=PatientOut)
async def update_patient(
    patient_id: str, payload: PatientUpdate, db: AsyncSession = Depends(get_db)
) -> PatientOut:
    """Update patient demographics or diabetes metadata fields."""

    patient = await service.get_patient(db, patient_id)
    if patient is None:
        raise HTTPException(status_code=404, detail="Patient not found")
    updated = await service.update_patient(db, patient, payload)
    return PatientOut.model_validate(updated)


@router.delete("/{patient_id}")
async def delete_patient(patient_id: str, db: AsyncSession = Depends(get_db)) -> dict[str, str]:
    """Delete patient and associated references according to governance policy."""

    patient = await service.get_patient(db, patient_id)
    if patient is None:
        raise HTTPException(status_code=404, detail="Patient not found")
    await service.delete_patient(db, patient)
    return {"status": "deleted"}


@router.get("/{patient_id}/history")
async def patient_history(patient_id: str, db: AsyncSession = Depends(get_db)) -> dict[str, object]:
    """Return patient prediction history timeline for longitudinal grade tracking."""

    result = await db.execute(
        select(Prediction)
        .where(Prediction.patient_id == patient_id)
        .order_by(Prediction.created_at.desc())
    )
    history_rows = list(result.scalars().all())
    history = [
        {
            "prediction_id": str(row.id),
            "dr_grade": row.dr_grade,
            "confidence": row.confidence,
            "model_used": row.model_used,
            "created_at": row.created_at.isoformat() if row.created_at else None,
            "is_reviewed": row.is_reviewed,
        }
        for row in history_rows
    ]

    return {"patient_id": patient_id, "history": history}
