# Generated by GitHub Copilot
from typing import Annotated

from fastapi import APIRouter, Depends, File, Form, Header, HTTPException, UploadFile
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.db.prediction import Prediction
from app.models.schemas.predict import PredictionResponse
from app.services.ml.inference import run_full_inference
from app.services.storage_service import StorageService

router = APIRouter()


@router.post("/analyze", response_model=PredictionResponse)
async def analyze_image(
    image: Annotated[UploadFile, File(...)],
    patient_id: Annotated[str | None, Form()] = None,
    model_preference: Annotated[str, Form()] = "auto",
    x_user_id: Annotated[str | None, Header()] = None,
    db: AsyncSession = Depends(get_db),
) -> PredictionResponse:
    """Analyze uploaded retinal image and return explainable DR prediction payload."""

    if image.content_type not in {
        "image/jpeg",
        "image/png",
        "image/tiff",
        "image/bmp",
        "application/dicom",
        "image/x-dicom",
    }:
        raise HTTPException(status_code=400, detail="Image format not supported")

    image_bytes = await image.read()
    if len(image_bytes) > 20 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="File size exceeds 20MB limit")

    storage = StorageService()
    return await run_full_inference(
        image_bytes=image_bytes,
        patient_id=patient_id,
        model_preference=model_preference,
        user_id=x_user_id or "00000000-0000-0000-0000-000000000000",
        db=db,
        storage=storage,
    )


@router.get("/{prediction_id}")
async def get_prediction(prediction_id: str, db: AsyncSession = Depends(get_db)) -> dict[str, object]:
    """Fetch prediction summary by identifier from persisted prediction records."""

    result = await db.execute(select(Prediction).where(Prediction.id == prediction_id))
    prediction = result.scalar_one_or_none()
    if prediction is None:
        raise HTTPException(status_code=404, detail="Prediction not found")

    return {
        "prediction_id": str(prediction.id),
        "patient_id": str(prediction.patient_id) if prediction.patient_id else None,
        "dr_grade": prediction.dr_grade,
        "confidence": prediction.confidence,
        "model_used": prediction.model_used,
        "created_at": prediction.created_at.isoformat() if prediction.created_at else None,
        "is_reviewed": prediction.is_reviewed,
        "doctor_notes": prediction.doctor_notes,
    }
