# Generated by GitHub Copilot
from datetime import datetime, timezone
from uuid import UUID, uuid4

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import get_db
from app.models.db.prediction import Prediction
from app.models.schemas.predict import (
    ClinicalPayload,
    ExplainabilityPayload,
    ImageQuality,
    PerformancePayload,
    PredictionResponse,
)
from app.services.report_service import ReportService

router = APIRouter()


@router.get("/{prediction_id}/download")
async def download_report(prediction_id: str, db: AsyncSession = Depends(get_db)) -> Response:
    """Generate and stream a PDF report for the specified prediction record."""

    report_service = ReportService()
    result = await db.execute(select(Prediction).where(Prediction.id == prediction_id))
    prediction = result.scalar_one_or_none()

    if prediction is None:
        raise HTTPException(status_code=404, detail="Prediction not found")

    sample = PredictionResponse(
        prediction_id=prediction.id if prediction.id else uuid4(),
        patient_id=prediction.patient_id,
        analyzed_by=str(prediction.analyzed_by) if prediction.analyzed_by else "system-user",
        timestamp=prediction.created_at or datetime.now(timezone.utc),
        model_used=prediction.model_used or "EfficientNetV2-B3",
        model_tier=prediction.model_tier or 2,
        image_quality=ImageQuality(
            blur_score=prediction.blur_score or 0.0,
            contrast_score=prediction.contrast_score or 0.0,
            brightness_mean=prediction.brightness_mean or 0.0,
            snr_score=prediction.snr_score or 0.0,
            composite_score=prediction.composite_quality or 0.0,
            quality_label=prediction.quality_label or "Acceptable",
            warning=None,
        ),
        preprocessing_applied=prediction.preprocessing_config or {},
        dr_grade=prediction.dr_grade,
        dr_label="Diabetic Retinopathy",
        dr_label_short=f"Grade {prediction.dr_grade}",
        confidence=prediction.confidence,
        class_probabilities=prediction.class_probabilities or {},
        explainability=ExplainabilityPayload(
            gradcam_overlay_b64="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=",
            gradcam_heatmap_b64="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=",
            gradcam_original_b64="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=",
            attention_regions=prediction.attention_regions or [],
            lime_explanation_b64="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=",
            shap_available=False,
        ),
        clinical=ClinicalPayload(
            recommendation=prediction.clinical_recommendation or "Clinical review required.",
            urgency=prediction.urgency_level or "routine",
            referral_guideline="AAO 2023",
            follow_up_months=prediction.follow_up_months or 1,
            disclaimer="This output is AI-generated and must be reviewed by a qualified ophthalmologist before any clinical decision.",
        ),
        performance=PerformancePayload(
            preprocessing_ms=prediction.preprocessing_ms or 0,
            inference_ms=prediction.inference_ms or 0,
            gradcam_ms=prediction.gradcam_ms or 0,
            lime_ms=prediction.lime_ms or 0,
            total_ms=prediction.total_ms or 0,
        ),
    )
    pdf_bytes = report_service.build_report(sample)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename=retinaiq_report_{prediction_id}.pdf"
        },
    )


@router.get("/patient/{patient_id}")
async def patient_reports(patient_id: str, db: AsyncSession = Depends(get_db)) -> dict[str, object]:
    """List available report metadata for all predictions under one patient."""

    try:
        patient_uuid = UUID(patient_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Invalid patient ID") from exc

    rows = await db.execute(
        select(Prediction)
        .where(Prediction.patient_id == patient_uuid)
        .order_by(Prediction.created_at.desc())
    )
    reports = [
        {
            "prediction_id": str(row.id),
            "dr_grade": row.dr_grade,
            "confidence": row.confidence,
            "created_at": row.created_at.isoformat() if row.created_at else None,
        }
        for row in rows.scalars().all()
    ]

    return {"patient_id": patient_id, "reports": reports}
