# Generated by GitHub Copilot
from fastapi import APIRouter

from app.api.v1.routes import annotations, auth, dashboard, health, patients, predict, reports

api_router = APIRouter()
api_router.include_router(health.router, tags=["health"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(predict.router, prefix="/predict", tags=["predict"])
api_router.include_router(patients.router, prefix="/patients", tags=["patients"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(annotations.router, tags=["annotations"])
