# Generated by GitHub Copilot
import pytest
from fastapi.testclient import TestClient

from app.main import app


@pytest.fixture()
def client() -> TestClient:
    """Return synchronous test client for API integration tests."""

    return TestClient(app)
