# Generated by GitHub Copilot

def test_patients_list_route(client) -> None:  # type: ignore[no-untyped-def]
    """Verify patients list endpoint responds without server failure."""

    response = client.get("/api/v1/patients")
    assert response.status_code == 200
