# Generated by GitHub Copilot
from app.core.security import create_access_token, get_token_subject


def test_jwt_roundtrip() -> None:
    """Ensure issued JWT can be decoded to original subject claim."""

    token = create_access_token("user-123")
    assert get_token_subject(token) == "user-123"
