# Generated by GitHub Copilot

def test_reports_patient_route(client) -> None:  # type: ignore[no-untyped-def]
    """Verify report list endpoint for patient responds successfully."""

    response = client.get("/api/v1/reports/patient/demo")
    assert response.status_code == 200
