# Generated by GitHub Copilot
from app.services.recommendation_engine import get_recommendation


def test_recommendation_has_urgency() -> None:
    """Ensure recommendation engine returns urgency field for each grade."""

    rec = get_recommendation(4)
    assert rec["urgency"] == "emergency"
