# Generated by GitHub Copilot
import numpy as np

from app.services.ml.quality_check import ImageQualityAssessor


def test_quality_assessor_outputs_scores() -> None:
    """Ensure quality assessor returns bounded composite score for RGB image."""

    image = np.ones((300, 300, 3), dtype=np.uint8) * 127
    result = ImageQualityAssessor().assess(image)
    assert 0 <= result.composite_score <= 100
