# Generated by GitHub Copilot
import numpy as np

from app.services.ml.gradcam import GradCAMExplainer


def test_attention_region_extraction_returns_bbox_dicts() -> None:
    """Validate extracted Grad-CAM attention regions include expected bbox keys."""

    heatmap = np.zeros((300, 300), dtype=np.float32)
    heatmap[100:140, 100:140] = 1.0
    regions = GradCAMExplainer._extract_attention_regions(  # type: ignore[misc]
        None, heatmap, (300, 300, 3)
    )
    assert isinstance(regions, list)
    if regions:
        assert {"x", "y", "w", "h"}.issubset(regions[0].keys())
