# Generated by GitHub Copilot
import numpy as np

from app.services.ml.preprocessor import AdaptivePreprocessor
from app.services.ml.quality_check import QualityScores


def test_auto_config_runs() -> None:
    """Verify preprocessor configuration branch executes with valid metric inputs."""

    config = AdaptivePreprocessor().auto_configure(
        QualityScores(120.0, 0.4, 0.5, 20.0, 70.0, "Good", None)
    )
    assert config.clahe_grid_size == (8, 8)


def test_preprocess_output_shape() -> None:
    """Validate preprocessing output batch shape and normalized range."""

    image = np.ones((512, 512, 3), dtype=np.uint8) * 120
    pre = AdaptivePreprocessor()
    config = pre.auto_configure(QualityScores(120.0, 0.4, 0.5, 20.0, 70.0, "Good", None))
    out = pre.preprocess(image, config)
    assert out.shape == (1, 300, 300, 3)
