# Generated by GitHub Copilot
import numpy as np

from app.services.ml.quality_check import ImageQualityAssessor


def test_quality_assessor_returns_valid_label() -> None:
    """Ensure image quality assessor emits one of supported quality labels."""

    image = np.ones((300, 300, 3), dtype=np.uint8) * 60
    label = ImageQualityAssessor().assess(image).quality_label
    assert label in {"Poor", "Acceptable", "Good"}
