# Generated by GitHub Copilot
import numpy as np

from app.services.ml.model_router import ModelTier, ServerContext, select_model_tier


def test_model_router_prefers_tier2_on_gpu_large_image() -> None:
    """Ensure router selects Tier-2 primary model when GPU exists and image is large."""

    image = np.zeros((500, 500, 3), dtype=np.uint8)
    context = ServerContext(gpu_available=True, queue_depth=0)
    assert select_model_tier(image, context) == ModelTier.TIER2_EFFICIENTNETV2_B3


def test_model_router_respects_override() -> None:
    """Ensure explicit user override forces requested model tier selection."""

    image = np.zeros((10, 10, 3), dtype=np.uint8)
    context = ServerContext(gpu_available=False, queue_depth=0, user_override="mobilenetv3")
    assert select_model_tier(image, context) == ModelTier.TIER1_MOBILENETV3
