# Generated by GitHub Copilot

def test_predict_route_exists(client) -> None:  # type: ignore[no-untyped-def]
    """Confirm predict endpoint path is registered and method constrained."""

    response = client.get("/api/v1/predict/analyze")
    assert response.status_code in {405, 422}
