# Generated by GitHub Copilot
from datetime import datetime

from pydantic import BaseModel, Field


class DoctorAnnotation(BaseModel):
    """Schema for clinician-authored review notes tied to predictions."""

    notes: str = Field(min_length=2, max_length=5000)


class AnnotationOut(BaseModel):
    """Schema returned after saving an annotation event."""

    prediction_id: str
    notes: str
    saved_at: datetime
