# Generated by GitHub Copilot
from pydantic import BaseModel, EmailStr, Field


class LoginRequest(BaseModel):
    """Schema for user login with email and password."""

    email: EmailStr
    password: str = Field(min_length=8)


class RegisterRequest(BaseModel):
    """Schema for user registration with role-bound profile info."""

    email: EmailStr
    full_name: str = Field(min_length=2)
    password: str = Field(min_length=8)
    role: str = "technician"


class TokenResponse(BaseModel):
    """Schema carrying access and refresh JWT tokens."""

    access_token: str
    refresh_token: str
    token_type: str = "bearer"
