# Generated by GitHub Copilot
from datetime import datetime

from pydantic import BaseModel


class DashboardStats(BaseModel):
    """Schema for dashboard KPIs and system status information."""

    total_scans: int
    scans_this_week: int
    scans_today: int
    average_confidence: float
    grade_distribution: dict[str, int]
    model_status: dict[str, object]


class RecentScan(BaseModel):
    """Schema for tabular representation of recent screening events."""

    prediction_id: str
    patient_name: str | None
    grade: int
    confidence: float
    model: str
    timestamp: datetime


class GradeDistribution(BaseModel):
    """Schema for aggregate grade counts for chart rendering."""

    counts: dict[str, int]
