# Generated by GitHub Copilot
from datetime import date, datetime
from uuid import UUID

from pydantic import BaseModel, Field


class PatientCreate(BaseModel):
    """Schema for creating a patient record."""

    patient_code: str | None = None
    full_name: str = Field(min_length=2)
    date_of_birth: date | None = None
    gender: str | None = None
    phone: str | None = None
    diabetes_type: str | None = None
    diabetes_duration_years: float | None = None
    hba1c_percent: float | None = None


class PatientUpdate(BaseModel):
    """Schema for partial updates to patient information."""

    full_name: str | None = None
    date_of_birth: date | None = None
    gender: str | None = None
    phone: str | None = None
    diabetes_type: str | None = None
    diabetes_duration_years: float | None = None
    hba1c_percent: float | None = None
    notes: str | None = None


class PatientOut(BaseModel):
    """Schema returned to clients for patient profile views."""

    id: UUID
    patient_code: str | None
    full_name: str
    date_of_birth: date | None
    gender: str | None
    phone: str | None
    diabetes_type: str | None
    diabetes_duration_years: float | None
    hba1c_percent: float | None
    notes: str | None = None
    created_at: datetime

    model_config = {"from_attributes": True}
