# Generated by GitHub Copilot
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel


class ImageQuality(BaseModel):
    """Image quality metrics computed before preprocessing."""

    blur_score: float
    contrast_score: float
    brightness_mean: float
    snr_score: float
    composite_score: float
    quality_label: str
    warning: str | None


class ExplainabilityPayload(BaseModel):
    """Encoded explainability artifacts and highlighted lesion regions."""

    gradcam_overlay_b64: str
    gradcam_heatmap_b64: str
    gradcam_original_b64: str
    attention_regions: list[dict[str, int]]
    lime_explanation_b64: str
    shap_available: bool


class ClinicalPayload(BaseModel):
    """Clinical recommendation data aligned to DR severity guidelines."""

    recommendation: str
    urgency: str
    referral_guideline: str
    follow_up_months: float
    disclaimer: str


class PerformancePayload(BaseModel):
    """Timing breakdown in milliseconds across inference pipeline stages."""

    preprocessing_ms: int
    inference_ms: int
    gradcam_ms: int
    lime_ms: int
    total_ms: int


class PredictionResponse(BaseModel):
    """Full response for retinal image analysis endpoint."""

    prediction_id: UUID
    patient_id: UUID | None
    analyzed_by: str
    timestamp: datetime
    model_used: str
    model_tier: int
    image_quality: ImageQuality
    preprocessing_applied: dict[str, object]
    dr_grade: int
    dr_label: str
    dr_label_short: str
    confidence: float
    class_probabilities: dict[str, float]
    explainability: ExplainabilityPayload
    clinical: ClinicalPayload
    performance: PerformancePayload


class PredictionSummary(BaseModel):
    """Lightweight list item representation of prior predictions."""

    prediction_id: UUID
    dr_grade: int
    confidence: float
    model_used: str
    created_at: datetime
