# Generated by GitHub Copilot
import base64

import cv2
import numpy as np
import tensorflow as tf


class GradCAMExplainer:
    """Generate class activation heatmaps and overlays for retinal lesion localization."""

    def __init__(self, model: tf.keras.Model, last_conv_layer_name: str) -> None:
        """Initialize explainer with model and last convolutional layer identifier."""

        self.model = model
        self.last_conv_layer_name = last_conv_layer_name

    def compute_heatmap(
        self,
        image_array: np.ndarray,
        pred_class_idx: int,
        sensitivity: float = 1.0,
    ) -> np.ndarray:
        """Return Grad-CAM heatmap normalized to [0, 1] for a target prediction class."""

        grad_model = tf.keras.models.Model(
            inputs=self.model.inputs,
            outputs=[self.model.get_layer(self.last_conv_layer_name).output, self.model.output],
        )
        with tf.GradientTape() as tape:
            conv_outputs, predictions = grad_model(image_array, training=False)
            loss = predictions[:, pred_class_idx]

        grads = tape.gradient(loss, conv_outputs)
        if grads is None:
            return np.zeros((300, 300), dtype=np.float32)
        pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
        conv_outputs = conv_outputs[0]
        heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
        heatmap = tf.squeeze(heatmap).numpy()
        heatmap = np.maximum(heatmap, 0)
        if heatmap.max() > 0:
            heatmap /= heatmap.max()
        heatmap = np.power(heatmap, 1.0 / max(sensitivity, 1e-6))
        return heatmap

    def overlay_on_image(
        self,
        original_image: np.ndarray,
        heatmap: np.ndarray,
        alpha: float = 0.45,
        colormap: int = cv2.COLORMAP_JET,
    ) -> np.ndarray:
        """Overlay resized heatmap onto RGB image and return BGR result for PNG encoding."""

        heatmap_resized = cv2.resize(heatmap, (original_image.shape[1], original_image.shape[0]))
        heatmap_uint8 = np.uint8(255 * heatmap_resized)
        heatmap_colored = cv2.applyColorMap(heatmap_uint8, colormap)
        original_bgr = cv2.cvtColor(original_image, cv2.COLOR_RGB2BGR)
        return cv2.addWeighted(original_bgr, 1 - alpha, heatmap_colored, alpha, 0)

    def generate_base64_overlay(
        self,
        original_image: np.ndarray,
        pred_class_idx: int,
        preprocessed_array: np.ndarray,
    ) -> dict[str, object]:
        """Generate base64 explainability assets and top attention regions for UI consumption."""

        heatmap = self.compute_heatmap(preprocessed_array, pred_class_idx)
        overlay = self.overlay_on_image(original_image, heatmap)
        heatmap_colored = cv2.applyColorMap(
            np.uint8(255 * cv2.resize(heatmap, (original_image.shape[1], original_image.shape[0]))),
            cv2.COLORMAP_JET,
        )

        def to_base64(img_bgr: np.ndarray) -> str:
            """Encode BGR image as data URL PNG for API transport."""

            _, buffer = cv2.imencode(".png", img_bgr)
            return "data:image/png;base64," + base64.b64encode(buffer).decode()

        attention_regions = self._extract_attention_regions(heatmap, original_image.shape)
        return {
            "overlay_b64": to_base64(overlay),
            "heatmap_only_b64": to_base64(heatmap_colored),
            "original_b64": to_base64(cv2.cvtColor(original_image, cv2.COLOR_RGB2BGR)),
            "attention_regions": attention_regions,
        }

    def _extract_attention_regions(self, heatmap: np.ndarray, img_shape: tuple[int, ...]) -> list[dict[str, int]]:
        """Extract top-3 largest high-activation bounding boxes from Grad-CAM heatmap."""

        threshold = 0.6
        binary = (cv2.resize(heatmap, (img_shape[1], img_shape[0])) > threshold).astype(np.uint8)
        contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        regions = [cv2.boundingRect(c) for c in contours]
        regions.sort(key=lambda r: r[2] * r[3], reverse=True)
        return [{"x": x, "y": y, "w": w, "h": h} for x, y, w, h in regions[:3]]
