# Generated by GitHub Copilot
import hashlib
import time
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

import numpy as np
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.db.audit_log import AuditLog
from app.models.db.prediction import Prediction
from app.models.schemas.predict import (
    ClinicalPayload,
    ExplainabilityPayload,
    ImageQuality,
    PerformancePayload,
    PredictionResponse,
)
from app.services.ml.model_loader import ModelRegistry
from app.services.ml.model_router import ServerContext, select_model_tier
from app.services.ml.preprocessor import AdaptivePreprocessor
from app.services.ml.quality_check import ImageQualityAssessor
from app.services.recommendation_engine import get_recommendation
from app.services.storage_service import StorageService

LABELS = {
    0: ("No Diabetic Retinopathy", "No DR"),
    1: ("Mild Diabetic Retinopathy", "Mild NPDR"),
    2: ("Moderate Diabetic Retinopathy", "Moderate NPDR"),
    3: ("Severe Diabetic Retinopathy", "Severe NPDR"),
    4: ("Proliferative Diabetic Retinopathy", "Proliferative DR"),
}


async def _build_cached_prediction_response(
    prediction: Prediction, storage: StorageService, user_id: str
) -> PredictionResponse:
    """Return a cached prediction response for an identical image hash."""

    artifacts = storage.fetch_prediction_artifacts(str(prediction.id))
    long_label, short_label = LABELS[prediction.dr_grade]

    return PredictionResponse(
        prediction_id=prediction.id,
        patient_id=prediction.patient_id,
        analyzed_by=str(prediction.analyzed_by) if prediction.analyzed_by else user_id,
        timestamp=prediction.created_at,
        model_used=prediction.model_used,
        model_tier=prediction.model_tier,
        image_quality=ImageQuality(
            blur_score=prediction.blur_score or 0.0,
            contrast_score=prediction.contrast_score or 0.0,
            brightness_mean=prediction.brightness_mean or 0.0,
            snr_score=prediction.snr_score or 0.0,
            composite_score=prediction.composite_quality or 0.0,
            quality_label=prediction.quality_label or "",
            warning=prediction.quality_warning,
        ),
        preprocessing_applied=prediction.preprocessing_config or {},
        dr_grade=prediction.dr_grade,
        dr_label=long_label,
        dr_label_short=short_label,
        confidence=prediction.confidence,
        class_probabilities=prediction.class_probabilities or {},
        explainability=ExplainabilityPayload(
            gradcam_overlay_b64=artifacts["overlay_b64"],
            gradcam_heatmap_b64=artifacts["heatmap_b64"],
            gradcam_original_b64=artifacts["original_b64"],
            attention_regions=prediction.attention_regions or [],
            lime_explanation_b64=artifacts["lime_b64"],
            shap_available=False,
        ),
        clinical=ClinicalPayload(
            recommendation=prediction.clinical_recommendation or "",
            urgency=prediction.urgency_level or "",
            referral_guideline=prediction.referral_guideline or "",
            follow_up_months=prediction.follow_up_months or 0.0,
            disclaimer="This output is AI-generated and must be reviewed by a qualified ophthalmologist before any clinical decision.",
        ),
        performance=PerformancePayload(
            preprocessing_ms=prediction.preprocessing_ms or 0,
            inference_ms=prediction.inference_ms or 0,
            gradcam_ms=prediction.gradcam_ms or 0,
            lime_ms=prediction.lime_ms or 0,
            total_ms=prediction.total_ms or 0,
        ),
    )


async def run_full_inference(
    image_bytes: bytes,
    patient_id: Optional[str],
    model_preference: str,
    user_id: str,
    db: AsyncSession,
    storage: StorageService,
) -> PredictionResponse:
    """Execute full analysis pipeline from bytes to explainable DR response payload."""

    total_start = time.perf_counter()
    image_hash = hashlib.sha256(image_bytes).hexdigest()

    existing_prediction = await db.execute(select(Prediction).where(Prediction.image_hash == image_hash))
    cached = existing_prediction.scalar_one_or_none()
    if cached is not None:
        return await _build_cached_prediction_response(cached, storage, user_id)

    preprocessor = AdaptivePreprocessor()
    quality_assessor = ImageQualityAssessor()
    registry = ModelRegistry.get_instance()

    decoded = preprocessor.decode_image(image_bytes)

    preprocess_start = time.perf_counter()
    quality = quality_assessor.assess(decoded)
    prep_config = preprocessor.auto_configure(quality)
    preprocessed_array = preprocessor.preprocess(decoded, prep_config)
    preprocessing_ms = int((time.perf_counter() - preprocess_start) * 1000)

    context = ServerContext(
        gpu_available=registry.gpu_available,
        queue_depth=0,
        user_override=model_preference if model_preference != "auto" else None,
    )
    tier = select_model_tier(decoded, context)
    loaded = registry.get_model(tier)

    inf_start = time.perf_counter()
    probs = loaded.model.predict(preprocessed_array, verbose=0)[0]
    dr_grade = int(np.argmax(probs))
    confidence = float(np.max(probs))
    inference_ms = int((time.perf_counter() - inf_start) * 1000)

    grad_start = time.perf_counter()
    grad_bundle = loaded.gradcam.generate_base64_overlay(
        original_image=decoded,
        pred_class_idx=dr_grade,
        preprocessed_array=preprocessed_array,
    )
    gradcam_ms = int((time.perf_counter() - grad_start) * 1000)

    lime_start = time.perf_counter()
    lime_input = preprocessed_array[0]
    lime_b64 = loaded.lime.explain(lime_input, pred_class_idx=dr_grade, num_samples=100)
    lime_ms = int((time.perf_counter() - lime_start) * 1000)

    recommendation = get_recommendation(dr_grade)

    image_hash = hashlib.sha256(image_bytes).hexdigest()
    prediction_id = await storage.store_prediction_artifacts(
        image_hash=image_hash,
        original_bytes=image_bytes,
        overlay_b64=str(grad_bundle["overlay_b64"]),
        heatmap_b64=str(grad_bundle["heatmap_only_b64"]),
        lime_b64=lime_b64,
    )

    class_probabilities = {
        "0_no_dr": float(probs[0]),
        "1_mild": float(probs[1]),
        "2_moderate": float(probs[2]),
        "3_severe": float(probs[3]),
        "4_proliferative": float(probs[4]),
    }

    patient_uuid: UUID | None = None
    if patient_id:
        try:
            patient_uuid = UUID(patient_id)
        except ValueError:
            patient_uuid = None

    analyzed_uuid: UUID | None = None
    try:
        analyzed_uuid = UUID(user_id)
    except ValueError:
        analyzed_uuid = None

    total_ms = int((time.perf_counter() - total_start) * 1000)

    prediction_row = Prediction(
        id=prediction_id,
        patient_id=patient_uuid,
        analyzed_by=analyzed_uuid,
        image_hash=image_hash,
        original_image_path=f"predictions/{prediction_id}/original.bin",
        gradcam_overlay_path=f"predictions/{prediction_id}/gradcam_overlay.png",
        gradcam_heatmap_path=f"predictions/{prediction_id}/gradcam_heatmap.png",
        lime_image_path=f"predictions/{prediction_id}/lime.png",
        blur_score=quality.blur_score,
        contrast_score=quality.contrast_score,
        brightness_mean=quality.brightness_mean,
        snr_score=quality.snr_score,
        composite_quality=quality.composite_score,
        quality_label=quality.quality_label,
        quality_warning=quality.warning,
        preprocessing_config={
            "clahe_clip_limit": prep_config.clahe_clip_limit,
            "clahe_grid_size": "8x8",
            "denoise_method": prep_config.denoise_method,
            "denoise_strength": prep_config.denoise_strength,
            "brightness_correction": prep_config.brightness_correction,
            "optic_disc_masked": prep_config.optic_disc_masked,
            "resize": prep_config.resize,
            "augmentations": prep_config.augmentations,
        },
        model_used=loaded.name,
        model_tier=loaded.tier,
        dr_grade=dr_grade,
        confidence=confidence,
        class_probabilities=class_probabilities,
        attention_regions=list(grad_bundle["attention_regions"]),
        clinical_recommendation=str(recommendation["text"]),
        urgency_level=str(recommendation["urgency"]),
        referral_guideline=str(recommendation["guideline"]),
        follow_up_months=float(recommendation["follow_up_months"]),
        preprocessing_ms=preprocessing_ms,
        inference_ms=inference_ms,
        gradcam_ms=gradcam_ms,
        lime_ms=lime_ms,
        total_ms=total_ms,
    )

    db.add(prediction_row)
    db.add(
        AuditLog(
            user_id=analyzed_uuid,
            action="inference",
            resource_type="prediction",
            resource_id=prediction_id,
            details={
                "model": loaded.name,
                "model_tier": loaded.tier,
                "quality_score": quality.composite_score,
                "dr_grade": dr_grade,
                "confidence": confidence,
            },
        )
    )
    await db.commit()

    long_label, short_label = LABELS[dr_grade]

    return PredictionResponse(
        prediction_id=prediction_id,
        patient_id=patient_uuid,
        analyzed_by=user_id,
        timestamp=datetime.now(timezone.utc),
        model_used=loaded.name,
        model_tier=loaded.tier,
        image_quality=ImageQuality(
            blur_score=quality.blur_score,
            contrast_score=quality.contrast_score,
            brightness_mean=quality.brightness_mean,
            snr_score=quality.snr_score,
            composite_score=quality.composite_score,
            quality_label=quality.quality_label,
            warning=quality.warning,
        ),
        preprocessing_applied={
            "clahe_clip_limit": prep_config.clahe_clip_limit,
            "clahe_grid_size": "8x8",
            "denoise_method": prep_config.denoise_method,
            "denoise_strength": prep_config.denoise_strength,
            "brightness_correction": prep_config.brightness_correction,
            "optic_disc_masked": prep_config.optic_disc_masked,
            "resize": prep_config.resize,
            "augmentations": prep_config.augmentations,
        },
        dr_grade=dr_grade,
        dr_label=long_label,
        dr_label_short=short_label,
        confidence=confidence,
        class_probabilities=class_probabilities,
        explainability=ExplainabilityPayload(
            gradcam_overlay_b64=str(grad_bundle["overlay_b64"]),
            gradcam_heatmap_b64=str(grad_bundle["heatmap_only_b64"]),
            gradcam_original_b64=str(grad_bundle["original_b64"]),
            attention_regions=list(grad_bundle["attention_regions"]),
            lime_explanation_b64=lime_b64,
            shap_available=False,
        ),
        clinical=ClinicalPayload(
            recommendation=recommendation["text"],
            urgency=recommendation["urgency"],
            referral_guideline=recommendation["guideline"],
            follow_up_months=float(recommendation["follow_up_months"]),
            disclaimer="This output is AI-generated and must be reviewed by a qualified ophthalmologist before any clinical decision.",
        ),
        performance=PerformancePayload(
            preprocessing_ms=preprocessing_ms,
            inference_ms=inference_ms,
            gradcam_ms=gradcam_ms,
            lime_ms=lime_ms,
            total_ms=total_ms,
        ),
    )
