# Generated by GitHub Copilot
import base64
from io import BytesIO
from typing import Callable

import numpy as np
from lime import lime_image
from PIL import Image
from skimage.segmentation import mark_boundaries


class LIMEExplainer:
    """Generate local superpixel explanations for model decisions on retinal scans."""

    def __init__(self, predict_fn: Callable[[np.ndarray], np.ndarray]) -> None:
        """Initialize LIME image explainer with model prediction wrapper."""

        self.explainer = lime_image.LimeImageExplainer()
        self.predict_fn = predict_fn

    def explain(
        self,
        image: np.ndarray,
        pred_class_idx: int,
        num_samples: int = 500,
        num_features: int = 10,
        hide_rest: bool = False,
    ) -> str:
        """Return base64 PNG LIME map with positive and negative superpixel boundaries."""

        explanation = self.explainer.explain_instance(
            image,
            self.predict_fn,
            top_labels=5,
            hide_color=0,
            num_samples=num_samples,
        )
        temp, mask = explanation.get_image_and_mask(
            pred_class_idx,
            positive_only=False,
            num_features=num_features,
            hide_rest=hide_rest,
        )
        marked = mark_boundaries(temp, mask)
        marked_uint8 = (marked * 255).astype(np.uint8)
        img_pil = Image.fromarray(marked_uint8)
        buffer = BytesIO()
        img_pil.save(buffer, format="PNG")
        return "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode()
