# Generated by GitHub Copilot
from dataclasses import dataclass
from enum import Enum

import numpy as np


class ModelTier(str, Enum):
    """Supported runtime model tiers across edge, hospital, and experimental modes."""

    TIER1_EFFICIENTNET_B0 = "tier1_efficientnet_b0"
    TIER1_MOBILENETV3 = "tier1_mobilenetv3"
    TIER2_EFFICIENTNETV2_B3 = "tier2_efficientnetv2_b3"
    TIER2_DENSENET121 = "tier2_densenet121"
    TIER3_CNN_VIT = "tier3_cnn_vit"


@dataclass(slots=True)
class ServerContext:
    """Operational server signals used for automatic model tier selection."""

    gpu_available: bool
    queue_depth: int
    user_override: str | None = None


def select_model_tier(image: np.ndarray, server_context: ServerContext) -> ModelTier:
    """Select model tier using image scale, hardware availability, load, and override."""

    override_map = {
        "tier1": ModelTier.TIER1_EFFICIENTNET_B0,
        "tier2": ModelTier.TIER2_EFFICIENTNETV2_B3,
        "efficientnetv2b3": ModelTier.TIER2_EFFICIENTNETV2_B3,
        "mobilenetv3": ModelTier.TIER1_MOBILENETV3,
        "efficientnetb0": ModelTier.TIER1_EFFICIENTNET_B0,
        "densenet121": ModelTier.TIER2_DENSENET121,
        "tier3": ModelTier.TIER3_CNN_VIT,
    }
    if server_context.user_override and server_context.user_override in override_map:
        return override_map[server_context.user_override]

    if server_context.queue_depth > 20:
        return ModelTier.TIER1_EFFICIENTNET_B0

    if server_context.gpu_available and image.size > 50000:
        return ModelTier.TIER2_EFFICIENTNETV2_B3
    if server_context.gpu_available:
        return ModelTier.TIER2_DENSENET121
    if image.size > 10000:
        return ModelTier.TIER1_EFFICIENTNET_B0
    return ModelTier.TIER1_MOBILENETV3
