# Generated by GitHub Copilot
import threading
from dataclasses import dataclass
from pathlib import Path
from time import perf_counter

import numpy as np
import tensorflow as tf

from app.core.config import get_settings
from app.services.ml.gradcam import GradCAMExplainer
from app.services.ml.lime_explainer import LIMEExplainer
from app.services.ml.model_router import ModelTier
from app.services.ml.training_bootstrap import ensure_primary_weights


@dataclass(slots=True)
class LoadedModel:
    """Container holding model and explainability helpers for a runtime tier."""

    model: tf.keras.Model
    gradcam: GradCAMExplainer
    lime: LIMEExplainer
    name: str
    tier: int


class ModelRegistry:
    """Thread-safe singleton for loading and serving all model tiers once per process."""

    _instance: "ModelRegistry | None" = None
    _lock = threading.Lock()

    def __init__(self) -> None:
        """Initialize model container and hardware capability flags."""

        self.settings = get_settings()
        self._models: dict[ModelTier, LoadedModel] = {}
        self.gpu_available = bool(tf.config.list_physical_devices("GPU"))

    @classmethod
    def get_instance(cls) -> "ModelRegistry":
        """Return singleton instance, loading model catalog on first call."""

        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = cls()
                    cls._instance._load_all_models()
        return cls._instance

    def _build_model(self, backbone: tf.keras.Model, output_classes: int = 5) -> tf.keras.Model:
        """Build unified classification head for each backbone architecture."""

        x = tf.keras.layers.GlobalAveragePooling2D()(backbone.output)
        x = tf.keras.layers.BatchNormalization()(x)
        x = tf.keras.layers.Dense(512, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
        x = tf.keras.layers.BatchNormalization()(x)
        x = tf.keras.layers.Dropout(0.5)(x)
        x = tf.keras.layers.Dense(256, activation="relu", kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
        x = tf.keras.layers.BatchNormalization()(x)
        x = tf.keras.layers.Dropout(0.4)(x)
        x = tf.keras.layers.Dense(128, activation="relu")(x)
        x = tf.keras.layers.Dropout(0.3)(x)
        output = tf.keras.layers.Dense(output_classes, activation="softmax")(x)
        return tf.keras.Model(inputs=backbone.input, outputs=output)

    def _load_all_models(self) -> None:
        """Load all configured tier models and attach Grad-CAM and LIME explainers."""

        ensure_primary_weights()
        model_dir = Path(self.settings.model_dir)
        model_dir.mkdir(parents=True, exist_ok=True)
        weights_lookup = {
            ModelTier.TIER1_EFFICIENTNET_B0: model_dir / self.settings.efficientnetb0_weights,
            ModelTier.TIER1_MOBILENETV3: model_dir / self.settings.mobilenetv3_weights,
            ModelTier.TIER2_EFFICIENTNETV2_B3: model_dir / self.settings.efficientnetv2b3_weights,
            ModelTier.TIER2_DENSENET121: model_dir / self.settings.densenet121_weights,
        }

        specs = [
            (ModelTier.TIER1_EFFICIENTNET_B0, "EfficientNet-B0", 1, tf.keras.applications.EfficientNetB0),
            (ModelTier.TIER1_MOBILENETV3, "MobileNetV3-Large", 1, tf.keras.applications.MobileNetV3Large),
            (ModelTier.TIER2_EFFICIENTNETV2_B3, "EfficientNetV2-B3", 2, tf.keras.applications.EfficientNetV2B3),
            (ModelTier.TIER2_DENSENET121, "DenseNet121", 2, tf.keras.applications.DenseNet121),
        ]

        for tier_key, name, tier_num, ctor in specs:
            start = perf_counter()
            backbone = ctor(weights=None, include_top=False, input_shape=(300, 300, 3))
            model = self._build_model(backbone)
            weights_path = weights_lookup.get(tier_key)
            if weights_path and weights_path.exists():
                model.load_weights(weights_path)
            last_conv = self._resolve_last_conv_layer(model)
            gradcam = GradCAMExplainer(model=model, last_conv_layer_name=last_conv)

            def predict_fn(batch: np.ndarray, m: tf.keras.Model = model) -> np.ndarray:
                """Wrap Keras predict for LIME integration with deterministic output type."""

                return m.predict(batch, verbose=0)

            lime = LIMEExplainer(predict_fn=predict_fn)
            self._models[tier_key] = LoadedModel(model=model, gradcam=gradcam, lime=lime, name=name, tier=tier_num)
            _ = (perf_counter() - start) * 1000

        # Experimental Tier-3 route currently reuses Tier-2 primary head for compatibility.
        self._models[ModelTier.TIER3_CNN_VIT] = self._models[ModelTier.TIER2_EFFICIENTNETV2_B3]

    def _resolve_last_conv_layer(self, model: tf.keras.Model) -> str:
        """Find the final convolution layer name for generic Grad-CAM extraction."""

        for layer in reversed(model.layers):
            if isinstance(layer, tf.keras.layers.Conv2D):
                return layer.name
        return model.layers[-2].name

    def get_model(self, tier: ModelTier) -> LoadedModel:
        """Return loaded model and explainers for requested runtime tier."""

        return self._models[tier]
