# Generated by GitHub Copilot
from dataclasses import dataclass
from io import BytesIO

import cv2
import magic
import numpy as np
import pydicom
from PIL import Image

from app.services.ml.quality_check import QualityScores


@dataclass(slots=True)
class PreprocessingConfig:
    """Resolved preprocessing parameters selected from image quality diagnostics."""

    clahe_clip_limit: float
    clahe_grid_size: tuple[int, int]
    denoise_method: str
    denoise_strength: str
    brightness_correction: bool
    optic_disc_masked: bool
    resize: str
    augmentations: list[str]


class AdaptivePreprocessor:
    """Robust image normalizer supporting fundus scans across formats and quality ranges."""

    def decode_image(self, image_bytes: bytes) -> np.ndarray:
        """Decode bytes into RGB ndarray using MIME sniffing and DICOM fallback support."""

        mime_type = magic.from_buffer(image_bytes, mime=True)
        if mime_type in {"application/dicom", "application/octet-stream", "image/x-dicom"}:
            ds = pydicom.dcmread(BytesIO(image_bytes), force=True)
            pixels = ds.pixel_array.astype(np.float32)
            pixels = (pixels - pixels.min()) / max((pixels.max() - pixels.min()), 1.0)
            gray8 = (pixels * 255.0).astype(np.uint8)
            rgb = cv2.cvtColor(gray8, cv2.COLOR_GRAY2RGB)
            return rgb

        pil_image = Image.open(BytesIO(image_bytes)).convert("RGB")
        return np.array(pil_image)

    def auto_configure(self, quality: QualityScores) -> PreprocessingConfig:
        """Choose CLAHE, denoise, and correction parameters from quality score thresholds."""

        if quality.contrast_score < 0.25:
            clip = 5.0
        elif quality.contrast_score < 0.45:
            clip = 3.0
        elif quality.contrast_score < 0.65:
            clip = 2.0
        else:
            clip = 1.0

        if quality.blur_score < 30:
            denoise_method = "bilateral"
            denoise_strength = "strong"
        elif quality.blur_score < 100:
            denoise_method = "gaussian"
            denoise_strength = "moderate"
        else:
            denoise_method = "none"
            denoise_strength = "none"

        brightness_correction = quality.brightness_mean < 0.2 or quality.brightness_mean > 0.8

        return PreprocessingConfig(
            clahe_clip_limit=clip,
            clahe_grid_size=(8, 8),
            denoise_method=denoise_method,
            denoise_strength=denoise_strength,
            brightness_correction=brightness_correction,
            optic_disc_masked=quality.composite_score > 60,
            resize="300x300",
            augmentations=[],
        )

    def preprocess(self, image_rgb: np.ndarray, config: PreprocessingConfig) -> np.ndarray:
        """Apply adaptive enhancements and return model-ready tensor in range [0, 1]."""

        work = image_rgb.copy()

        if config.brightness_correction:
            gamma = 0.5 if work.mean() / 255.0 < 0.2 else 1.5
            inv_gamma = 1.0 / gamma
            table = np.array([((i / 255.0) ** inv_gamma) * 255 for i in range(256)]).astype(np.uint8)
            work = cv2.LUT(work, table)

        if config.denoise_method == "bilateral":
            work = cv2.bilateralFilter(work, d=9, sigmaColor=75, sigmaSpace=75)
        elif config.denoise_method == "gaussian":
            work = cv2.GaussianBlur(work, (3, 3), 0.8)

        b, g, r = cv2.split(work)
        clahe = cv2.createCLAHE(
            clipLimit=config.clahe_clip_limit, tileGridSize=config.clahe_grid_size
        )
        g = clahe.apply(g)
        work = cv2.merge([b, g, r])

        work = self._smart_resize(work, target_size=300)
        normalized = work.astype(np.float32) / 255.0
        return np.expand_dims(normalized, axis=0)

    def _smart_resize(self, image: np.ndarray, target_size: int) -> np.ndarray:
        """Preserve aspect ratio via center crop before high-quality resize to target input."""

        h, w = image.shape[:2]
        if h == w:
            cropped = image
        elif h > w:
            start = (h - w) // 2
            cropped = image[start : start + w, :]
        else:
            start = (w - h) // 2
            cropped = image[:, start : start + h]

        interpolation = cv2.INTER_AREA if cropped.shape[0] > target_size else cv2.INTER_CUBIC
        return cv2.resize(cropped, (target_size, target_size), interpolation=interpolation)
