# Generated by GitHub Copilot
from dataclasses import dataclass

import cv2
import numpy as np
from skimage.restoration import estimate_sigma


@dataclass(slots=True)
class QualityScores:
    """Quality metrics extracted from retinal scan for adaptive processing controls."""

    blur_score: float
    contrast_score: float
    brightness_mean: float
    snr_score: float
    composite_score: float
    quality_label: str
    warning: str | None


class ImageQualityAssessor:
    """Assess retinal image quality to drive robust adaptive preprocessing decisions."""

    def assess(self, image_rgb: np.ndarray) -> QualityScores:
        """Compute blur, contrast, brightness, and SNR with normalized composite score."""

        gray = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY)
        blur_score = float(cv2.Laplacian(gray, cv2.CV_64F).var())
        contrast_score = float(gray.std() / 255.0)
        brightness_mean = float(gray.mean() / 255.0)

        sigma = estimate_sigma(gray.astype(np.float32) / 255.0, channel_axis=None, average_sigmas=True)
        signal = float(np.mean(gray.astype(np.float32)) + 1e-6)
        noise = float(max(sigma * 255.0, 1e-6))
        snr_score = float(signal / noise)

        blur_norm = min(blur_score / 200.0, 1.0)
        contrast_norm = min(contrast_score / 0.65, 1.0)
        brightness_norm = 1.0 - min(abs(brightness_mean - 0.5) / 0.5, 1.0)
        snr_norm = min(snr_score / 30.0, 1.0)
        composite = float((0.35 * blur_norm + 0.25 * contrast_norm + 0.2 * brightness_norm + 0.2 * snr_norm) * 100)

        if composite < 40:
            label = "Poor"
            warning = "Low quality image detected. AI results may have reduced accuracy."
        elif composite < 70:
            label = "Acceptable"
            warning = None
        else:
            label = "Good"
            warning = None

        return QualityScores(
            blur_score=blur_score,
            contrast_score=contrast_score,
            brightness_mean=brightness_mean,
            snr_score=snr_score,
            composite_score=composite,
            quality_label=label,
            warning=warning,
        )
