# Generated by GitHub Copilot
import base64
from io import BytesIO

import matplotlib.pyplot as plt
import numpy as np


class SHAPExplainer:
    """Metadata explainer fallback that produces feature-importance visualization."""

    def explain_metadata(self, features: dict[str, float]) -> str:
        """Create a compact feature bar chart as base64 PNG when metadata exists."""

        if not features:
            return ""

        keys = list(features.keys())
        values = np.array(list(features.values()), dtype=float)
        if values.sum() <= 0:
            values = np.ones_like(values)
        weights = values / values.sum()

        fig, ax = plt.subplots(figsize=(6, 3))
        ax.barh(keys, weights, color="#00D4AA")
        ax.set_xlabel("Relative Contribution")
        ax.set_title("Metadata Risk Contribution")
        fig.tight_layout()

        buffer = BytesIO()
        fig.savefig(buffer, format="png", dpi=150)
        plt.close(fig)
        return "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode()
