# Generated by GitHub Copilot
import subprocess
import sys
from pathlib import Path

from app.core.config import get_settings


def ensure_primary_weights() -> None:
    """Train primary model automatically when configured and weights are not available."""

    settings = get_settings()
    model_dir = Path(settings.model_dir)
    model_dir.mkdir(parents=True, exist_ok=True)

    target_weights = model_dir / settings.efficientnetv2b3_weights
    if target_weights.exists() or not settings.auto_train_if_missing:
        return

    dataset_path = settings.dataset_path.strip()
    if not dataset_path:
        raise RuntimeError(
            "Primary model weights are missing and DATASET_PATH is not configured. "
            "Set DATASET_PATH in .env to enable auto-training."
        )

    train_script = Path(__file__).resolve().parents[3] / "ml_models" / "train.py"
    command = [
        sys.executable,
        str(train_script),
        "--dataset_path",
        dataset_path,
        "--model",
        "efficientnetv2b3",
        "--epochs",
        str(settings.train_on_start_epochs),
        "--batch_size",
        str(settings.train_on_start_batch_size),
        "--output",
        str(target_weights),
    ]

    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(
            "Auto-training failed. "
            f"stdout={result.stdout}\n"
            f"stderr={result.stderr}"
        )

    if not target_weights.exists():
        raise RuntimeError(
            f"Auto-training completed but expected weights were not created: {target_weights}"
        )
