# Generated by GitHub Copilot
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.db.patient import Patient
from app.models.schemas.patient import PatientCreate, PatientUpdate


class PatientService:
    """CRUD service layer for patient entities with async SQLAlchemy operations."""

    async def list_patients(self, db: AsyncSession) -> list[Patient]:
        """Return all patients ordered by most recently updated first."""

        result = await db.execute(select(Patient).order_by(Patient.updated_at.desc()))
        return list(result.scalars().all())

    async def create_patient(self, db: AsyncSession, payload: PatientCreate) -> Patient:
        """Persist and return a new patient record from validated payload."""

        patient = Patient(**payload.model_dump())
        db.add(patient)
        await db.commit()
        await db.refresh(patient)
        return patient

    async def get_patient(self, db: AsyncSession, patient_id: str) -> Patient | None:
        """Fetch a single patient by UUID string."""

        result = await db.execute(select(Patient).where(Patient.id == patient_id))
        return result.scalar_one_or_none()

    async def update_patient(self, db: AsyncSession, patient: Patient, payload: PatientUpdate) -> Patient:
        """Apply partial update fields and return refreshed patient instance."""

        for key, value in payload.model_dump(exclude_unset=True).items():
            setattr(patient, key, value)
        await db.commit()
        await db.refresh(patient)
        return patient

    async def delete_patient(self, db: AsyncSession, patient: Patient) -> None:
        """Delete patient record from persistence storage."""

        await db.delete(patient)
        await db.commit()
