# Generated by GitHub Copilot
CLINICAL_RECOMMENDATIONS = {
    0: {
        "text": "No diabetic retinopathy detected. Continue routine annual screening.",
        "urgency": "none",
        "follow_up_months": 12,
        "guideline": "AAO 2023 - annual screening for all diabetic patients",
    },
    1: {
        "text": "Mild NPDR detected. Optimize glycemic and blood pressure control. Repeat screening in 12 months.",
        "urgency": "routine",
        "follow_up_months": 12,
        "guideline": "AAO 2023 - mild NPDR annual follow-up",
    },
    2: {
        "text": "Moderate NPDR detected. Refer to ophthalmologist within 1 month for detailed dilated exam.",
        "urgency": "moderate",
        "follow_up_months": 1,
        "guideline": "AAO 2023 - moderate NPDR referral within 1 month",
    },
    3: {
        "text": "Severe NPDR detected. Urgent referral to ophthalmologist required within 1 week.",
        "urgency": "urgent",
        "follow_up_months": 0.25,
        "guideline": "AAO 2023 / NICE NG28 - severe NPDR urgent referral",
    },
    4: {
        "text": "Proliferative DR detected. Immediate specialist referral is required today.",
        "urgency": "emergency",
        "follow_up_months": 0,
        "guideline": "AAO 2023 / NICE NG28 - PDR same-day referral",
    },
}


def get_recommendation(dr_grade: int) -> dict[str, object]:
    """Return guideline-aligned recommendation object for predicted DR grade."""

    return CLINICAL_RECOMMENDATIONS.get(dr_grade, CLINICAL_RECOMMENDATIONS[0])
