# Generated by GitHub Copilot
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

from app.models.schemas.predict import PredictionResponse


class ReportService:
    """Generate multi-page PDF reports for explainable DR screening outcomes."""

    def build_report(self, response: PredictionResponse) -> bytes:
        """Render three-page clinical report PDF and return binary document payload."""

        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        self._draw_page_one(pdf, width, height, response)
        pdf.showPage()
        self._draw_page_two(pdf, width, height, response)
        pdf.showPage()
        self._draw_page_three(pdf, width, height, response)

        pdf.save()
        return buffer.getvalue()

    def _draw_page_one(self, pdf: canvas.Canvas, width: float, height: float, response: PredictionResponse) -> None:
        """Draw summary and patient context on first report page."""

        pdf.setFillColor(colors.HexColor("#0A0F1E"))
        pdf.rect(0, height - 80, width, 80, fill=1, stroke=0)
        pdf.setFillColor(colors.white)
        pdf.setFont("Helvetica-Bold", 20)
        pdf.drawString(40, height - 50, "RetinaIQ")

        pdf.setFillColor(colors.black)
        pdf.setFont("Helvetica", 11)
        pdf.drawString(40, height - 120, f"Prediction ID: {response.prediction_id}")
        pdf.drawString(40, height - 140, f"Model: {response.model_used}")
        pdf.drawString(40, height - 160, f"Quality: {response.image_quality.composite_score:.1f}")

        pdf.setFont("Helvetica-Bold", 52)
        pdf.drawString(40, height - 260, f"Grade {response.dr_grade}")
        pdf.setFont("Helvetica", 16)
        pdf.drawString(40, height - 290, response.dr_label_short)
        pdf.drawString(40, height - 320, f"Confidence: {response.confidence * 100:.1f}%")

    def _draw_page_two(self, pdf: canvas.Canvas, width: float, height: float, response: PredictionResponse) -> None:
        """Draw visual evidence page with original and Grad-CAM overlay outputs."""

        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(40, height - 50, "Visual Evidence")
        left_image = ImageReader(BytesIO(self._decode_data_uri(response.explainability.gradcam_original_b64)))
        right_image = ImageReader(BytesIO(self._decode_data_uri(response.explainability.gradcam_overlay_b64)))
        pdf.drawImage(left_image, 40, height - 370, width=240, height=240, preserveAspectRatio=True)
        pdf.drawImage(right_image, 320, height - 370, width=240, height=240, preserveAspectRatio=True)

    def _draw_page_three(self, pdf: canvas.Canvas, width: float, height: float, response: PredictionResponse) -> None:
        """Draw probabilities, recommendation, and mandatory medical disclaimer."""

        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(40, height - 50, "Clinical Recommendation")
        pdf.setFont("Helvetica", 12)
        pdf.drawString(40, height - 80, response.clinical.recommendation)
        pdf.drawString(40, height - 105, f"Urgency: {response.clinical.urgency}")
        pdf.drawString(40, height - 130, f"Guideline: {response.clinical.referral_guideline}")

        pdf.setFillColor(colors.HexColor("#FDECEC"))
        pdf.rect(40, height - 250, width - 80, 90, fill=1, stroke=0)
        pdf.setFillColor(colors.black)
        pdf.setFont("Helvetica", 10)
        pdf.drawString(50, height - 200, response.clinical.disclaimer)

    def _decode_data_uri(self, data_uri: str) -> bytes:
        """Decode data URL image field into PNG bytes for ReportLab embedding."""

        import base64

        return base64.b64decode(data_uri.split(",", maxsplit=1)[1])
