# Generated by GitHub Copilot
import base64
import uuid
from io import BytesIO

from minio import Minio

from app.core.config import get_settings


class StorageService:
    """S3-compatible artifact storage for retinal images and explainability outputs."""

    def __init__(self) -> None:
        """Initialize MinIO client and ensure private prediction bucket exists."""

        settings = get_settings()
        self.bucket = settings.minio_bucket_name
        self.client = Minio(
            endpoint=settings.minio_endpoint,
            access_key=settings.minio_access_key,
            secret_key=settings.minio_secret_key,
            secure=settings.minio_secure,
        )
        if not self.client.bucket_exists(self.bucket):
            self.client.make_bucket(self.bucket)

    def _upload_bytes(self, object_name: str, payload: bytes, content_type: str) -> None:
        """Upload binary payload to object storage with explicit content metadata."""

        self.client.put_object(
            bucket_name=self.bucket,
            object_name=object_name,
            data=BytesIO(payload),
            length=len(payload),
            content_type=content_type,
        )

    def _download_bytes(self, object_name: str) -> bytes:
        """Download stored artifact bytes from object storage."""

        obj = self.client.get_object(bucket_name=self.bucket, object_name=object_name)
        try:
            return obj.read()
        finally:
            obj.close()
            obj.release_conn()

    def _guess_image_mime_type(self, payload: bytes) -> str:
        """Infer the original image MIME type from the binary header."""

        if payload.startswith(b"\x89PNG\r\n\x1a\n"):
            return "image/png"
        if payload.startswith(b"\xff\xd8\xff"):
            return "image/jpeg"
        if payload.startswith(b"II*\x00") or payload.startswith(b"MM\x00*"):
            return "image/tiff"
        return "application/octet-stream"

    def fetch_prediction_artifacts(self, prediction_id: str) -> dict[str, str]:
        """Load stored explainability artifacts for a completed prediction."""

        prefix = f"predictions/{prediction_id}"
        original_bytes = self._download_bytes(f"{prefix}/original.bin")
        overlay_bytes = self._download_bytes(f"{prefix}/gradcam_overlay.png")
        heatmap_bytes = self._download_bytes(f"{prefix}/gradcam_heatmap.png")
        lime_bytes = self._download_bytes(f"{prefix}/lime.png")

        original_mime = self._guess_image_mime_type(original_bytes)
        return {
            "overlay_b64": "data:image/png;base64," + base64.b64encode(overlay_bytes).decode(),
            "heatmap_b64": "data:image/png;base64," + base64.b64encode(heatmap_bytes).decode(),
            "lime_b64": "data:image/png;base64," + base64.b64encode(lime_bytes).decode(),
            "original_b64": f"data:{original_mime};base64," + base64.b64encode(original_bytes).decode(),
        }

    async def store_prediction_artifacts(
        self,
        image_hash: str,
        original_bytes: bytes,
        overlay_b64: str,
        heatmap_b64: str,
        lime_b64: str,
    ) -> uuid.UUID:
        """Persist all artifacts and return generated prediction identifier."""

        prediction_id = uuid.uuid4()
        prefix = f"predictions/{prediction_id}"

        self._upload_bytes(f"{prefix}/original.bin", original_bytes, "application/octet-stream")
        self._upload_bytes(
            f"{prefix}/gradcam_overlay.png",
            base64.b64decode(overlay_b64.split(",", maxsplit=1)[1]),
            "image/png",
        )
        self._upload_bytes(
            f"{prefix}/gradcam_heatmap.png",
            base64.b64decode(heatmap_b64.split(",", maxsplit=1)[1]),
            "image/png",
        )
        self._upload_bytes(
            f"{prefix}/lime.png",
            base64.b64decode(lime_b64.split(",", maxsplit=1)[1]),
            "image/png",
        )
        self._upload_bytes(f"{prefix}/hash.txt", image_hash.encode("utf-8"), "text/plain")
        return prediction_id
