# Generated by GitHub Copilot
from celery import Celery

from app.core.config import get_settings

settings = get_settings()
celery_app = Celery(
    "retinaiq",
    broker=settings.celery_broker_url,
    backend=settings.celery_result_backend,
)
celery_app.conf.task_routes = {"app.tasks.inference_task.async_analyze_image": {"queue": "inference"}}
