# Generated by GitHub Copilot
from datetime import datetime, timezone

from app.tasks.celery_app import celery_app


@celery_app.task(name="app.tasks.inference_task.async_analyze_image")
def async_analyze_image(payload: dict[str, str]) -> dict[str, str]:
    """Queue-aware inference task envelope returning lifecycle metadata."""

    now = datetime.now(timezone.utc).isoformat()
    return {
        "status": "accepted",
        "received_at": now,
        "task_name": "app.tasks.inference_task.async_analyze_image",
        "payload_keys": ",".join(sorted(payload.keys())),
    }
