# Generated by GitHub Copilot
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from prometheus_fastapi_instrumentator import Instrumentator

from app.api.v1.router import api_router
from app.core.config import get_settings
from app.core.logging import RequestIdLogMiddleware, configure_logger
from app.middleware.timing import TimingMiddleware
from app.services.ml.model_loader import ModelRegistry

settings = get_settings()


@asynccontextmanager
async def lifespan(_: FastAPI):
    """Initialize logging and model registry at startup for warm inference readiness."""

    configure_logger()
    ModelRegistry.get_instance()
    yield


app = FastAPI(title=settings.app_name, debug=settings.debug, lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[settings.frontend_url],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(RequestIdLogMiddleware)
app.add_middleware(TimingMiddleware)

Instrumentator().instrument(app).expose(app)
app.include_router(api_router, prefix="/api/v1")
