# Generated by GitHub Copilot
import time

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request


class TimingMiddleware(BaseHTTPMiddleware):
    """Attach request processing duration for observability and performance audits."""

    async def dispatch(self, request: Request, call_next):  # type: ignore[override]
        """Measure request time and expose in response headers."""

        start = time.perf_counter()
        response = await call_next(request)
        response.headers["X-Process-Time-MS"] = str(int((time.perf_counter() - start) * 1000))
        return response
