# Generated by GitHub Copilot
from functools import lru_cache
from typing import Literal

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings loaded from environment variables."""

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    app_name: str = "RetinaIQ"
    app_env: Literal["development", "production"] = "development"
    debug: bool = True
    frontend_url: str = "http://localhost:3000"

    secret_key: str = Field("supersecret-change-me", alias="SECRET_KEY")
    algorithm: str = "HS256"
    access_token_expire_minutes: int = 30
    refresh_token_expire_days: int = 7

    db_host: str = "postgres"
    db_port: int = 5432
    db_name: str = "retinaiq"
    db_user: str = "retinaiq_user"
    db_password: str = "retinaiq_password"
    database_url: str = "postgresql+asyncpg://retinaiq_user:retinaiq_password@postgres:5432/retinaiq"

    redis_url: str = "redis://redis:6379/0"
    cache_ttl_seconds: int = 3600

    storage_backend: Literal["minio", "s3"] = "minio"
    minio_endpoint: str = "minio:9000"
    minio_access_key: str = "minioadmin"
    minio_secret_key: str = "minioadmin123"
    minio_bucket_name: str = "retinaiq-images"
    minio_secure: bool = False

    model_dir: str = "/app/ml_models"
    default_model_tier: int = 2
    auto_train_if_missing: bool = True
    dataset_path: str = ""
    train_on_start_epochs: int = 5
    train_on_start_batch_size: int = 16
    efficientnetv2b3_weights: str = "retinaiq_efficientnetv2b3.weights.h5"
    efficientnetb0_weights: str = "retinaiq_efficientnetb0.weights.h5"
    mobilenetv3_weights: str = "retinaiq_mobilenetv3.weights.h5"
    densenet121_weights: str = "retinaiq_densenet121.weights.h5"
    image_quality_threshold: int = 40
    max_upload_size_mb: int = 20

    celery_broker_url: str = "redis://redis:6379/1"
    celery_result_backend: str = "redis://redis:6379/2"

    log_level: str = "INFO"
    log_format: Literal["json", "text"] = "json"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Return process-wide cached settings instance."""

    return Settings()
