# Generated by GitHub Copilot
from fastapi import HTTPException


class BadRequestException(HTTPException):
    """Raise HTTP 400 errors for invalid request payloads or business rules."""

    def __init__(self, detail: str) -> None:
        super().__init__(status_code=400, detail=detail)


class UnauthorizedException(HTTPException):
    """Raise HTTP 401 errors for failed authentication."""

    def __init__(self, detail: str = "Unauthorized") -> None:
        super().__init__(status_code=401, detail=detail)


class ForbiddenException(HTTPException):
    """Raise HTTP 403 errors for role-based access denials."""

    def __init__(self, detail: str = "Forbidden") -> None:
        super().__init__(status_code=403, detail=detail)


class NotFoundException(HTTPException):
    """Raise HTTP 404 errors for missing entities."""

    def __init__(self, detail: str) -> None:
        super().__init__(status_code=404, detail=detail)
