# Generated by GitHub Copilot
import sys
import uuid
from contextvars import ContextVar

from loguru import logger
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request

request_id_ctx_var: ContextVar[str] = ContextVar("request_id", default="-")


class RequestIdLogMiddleware(BaseHTTPMiddleware):
    """Attach request ID context for structured logs and response tracing."""

    async def dispatch(self, request: Request, call_next):  # type: ignore[override]
        """Set and propagate request identifier per request lifecycle."""

        request_id = request.headers.get("x-request-id", str(uuid.uuid4()))
        token = request_id_ctx_var.set(request_id)
        response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        request_id_ctx_var.reset(token)
        return response


def configure_logger() -> None:
    """Configure Loguru with compact JSON output for observability pipelines."""

    logger.remove()
    logger.add(sys.stdout, serialize=True, backtrace=False, diagnose=False)


def get_logger():
    """Return logger pre-bound with current request id context."""

    return logger.bind(request_id=request_id_ctx_var.get())
